### ISSUE TITLE
FR6. Page to view FAQs

### ISSUE THREAD

**Issue by gv7491** [WSU-4110/Breaking-Bets#10]
|FR6.  Page to view FAQs.|
|---|
|**Goal**: A dedicated page where FAQs are displayed. 
**Stakeholders:** User|
| **Description:** Users will be able to access our FAQs section through a button displayed at the bottom of each page. This page will give information is commonly asked through our contact page, as well as information our team thinks will help the user. |
| **Version:** 1.0  |
|**Date:** 09/28/2021|
  **Priority:** 1 |

**Comment by GoBlue734** [comment]
Added information to FAQ page. User can now view this information through our website.
