### ISSUE TITLE
NR1. Easy to Use Website Interface

### ISSUE THREAD

**Issue by fz9981** [WSU-4110/Breaking-Bets#12]
|NR1.  Easy to Use Website Interface|
|---|
|**Goal**: The website will be designed with user convenience in mind.  
**Stakeholders:**  Front-End Developers |
| **Description:** The website will be designed in a way that is easy for the users to understand and follow. It should be convenient for the user to find the information they are looking for.     |
| **Origin:** Team members came up with this requirement during the first meeting..|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
**Priority:** 3 |

**Comment by GoBlue734** [comment]
Noah put together an easy to use interface for the user.
