### ISSUE TITLE
FR10. Actively update news section.

### ISSUE THREAD

**Issue by gv7491** [WSU-4110/Breaking-Bets#21]
|FR10. Actively update news section.|
|---|
|**Goal**:  Our news section will update shortly after breaking news occurs. 
**Stakeholders:** User|
| **Description:** This feature will require getting up-to-date news and presenting it to the user. A free scraping tool will be used to retrieve and display current relevant news articles. |
| **Origin:** This was determined in the initial proposal that was selected and confirmed as a team while planning our initial presentation. |
| **Version:** 1.0  |
|**Date:** 09/28/2021|
  **Priority:** 1 |

**Comment by fy2906** [comment]
Implemented with commit https://github.com/WSU-4110/Breaking-Bets/commit/bd29ab0c35b75f828ca5d9a2a165e29cf950265a
