### ISSUE TITLE
FR2. Page to view team information.

### ISSUE THREAD

**Issue by gv7491** [WSU-4110/Breaking-Bets#3]
|FR2.  Page to view team information.|
|---|
|**Goal**: Each team will have their own dedicated page displaying their information. 
**Stakeholders:** User|
| **Description:** Users will be able to click on a team name and be directed to the team’s page. This page will display statistics about the team, as well as some information related to their upcoming opponent. This page will also have information about the team’s injuries, and a further interesting find that we came up with while sorting the data. |
| **Origin:** The team came up with this requirement while planning our initial presentation. |
| **Version:** 1.0  |
|**Date:** 09/28/2021|
  **Priority:** 1 |

**Comment by fz9981** [comment]
This can be seen on the homepage. Completed
