### ISSUE TITLE
FR4. Page to view breaking news.

### ISSUE THREAD

**Issue by gv7491** [WSU-4110/Breaking-Bets#5]
|FR4. Page to view breaking news.|
|---|
|**Goal**: A dedicated page for users to view relevant breaking news.
**Stakeholders:** User|
| **Description:** Users will be able to access our dedicated breaking news page through a button at the top of the page. This news will mainly pertain to injuries. Breaking news will also be displayed on our home page. |
| **Origin:** This was determined in the initial proposal that was selected and confirmed as a team while planning our initial presentation. |
| **Version:** 1.0  |
|**Date:** 09/28/2021|
  **Priority:** 1 |

**Comment by fy2906** [comment]
Implemented with commit https://github.com/WSU-4110/Breaking-Bets/commit/bd29ab0c35b75f828ca5d9a2a165e29cf950265a
