### ISSUE TITLE
NR5. Website Performance

### ISSUE THREAD

**Issue by fz9981** [WSU-4110/Breaking-Bets#6]
|NR5.  Website Performance|
|---|
|**Goal**: This website should have strong performance. 
**Stakeholders:** All|
| **Description:** All aspects of this website must demonstrate strong performance in order to efficiently retrieve information and display this information to the user. This requires getting information to the user quickly and correctly.   |
| **Origin:** Team members came up with this requirement during the first meeting..|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
**Priority:** 1 |

**Comment by GoBlue734** [comment]
Live news functions well. Our data is only 12-24 hours behind.
