### ISSUE TITLE
NR4. Protecting User Privacy

### ISSUE THREAD

**Issue by fz9981** [WSU-4110/Breaking-Bets#7]
|NR4.  Protecting User Privacy|
|---|
|**Goal**: User privacy will be protected.  
**Stakeholders:** All|
| **Description:** No aspect of this website will store or track any user information. No user information will be required for this website to function.     |
| **Origin:** Team members came up with this requirement during the first meeting..|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
**Priority:** 1 |

**Comment by GoBlue734** [comment]
We don't have login or payment information from the user. Contact info is emailed directly to us.
