### ISSUE TITLE
FR5. Page to view contact information.

### ISSUE THREAD

**Issue by gv7491** [WSU-4110/Breaking-Bets#8]
|FR5.  Page to view contact information.|
|---|
|**Goal**: A dedicated page for the user to contact support. 
**Stakeholders:** User|
| **Description:** Users will be able to access our contact page through a button displayed at the bottom of each page. This page will ask the user to enter their information along with the issue that they are having. The team will be able to respond through the given contact info.  |
| **Version:** 1.0  |
|**Date:** 09/28/2021|
  **Priority:** 1 |

**Comment by fy2906** [comment]
Implemented as a contact form page.
