### ISSUE TITLE
NR3. Website Reliability

### ISSUE THREAD

**Issue by fz9981** [WSU-4110/Breaking-Bets#9]
|NR3.  Website Reliability|
|---|
|**Goal**: The website should be reliable
**Stakeholders:** All|
| **Description:** This website should be able to perform the required functions based on the priority of the functions. A higher priority function will be more important to be reliable than a lower priority function.    |
| **Origin:** Team members came up with this requirement during the first meeting..|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
**Priority:** 1 |

**Comment by GoBlue734** [comment]
The website works, we would like to have more functionality but the site is reliable.
